version: 2.1

orbs:
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  build:
    docker:
      - image: cimg/python:3.11
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: workoutshare_admin
      - image: cimg/python:3.11.0-browsers

    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: install dependencies
          command: |
            pip install packaging
            pip install webdriver-manager
            pip install selenium
      - run:
          command: pip install pipenv
          name: Install pipenv
      - run:
          command: pipenv install --dev
          name: Install dependencies
      - run:
          command: pipenv run pytest --cov 
          name: Test
      - run:
          command: pipenv run pylint ./workoutshare
          name: Lint
workflows:
  main:
    jobs:
      - build
