version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: workoutshare_admin
      - image: cimg/node:16.13.1-browsers

    steps:
      - checkout
      - run:
          command: pip install pipenv
          name: Install pipenv
      - run:
          command: pipenv install --dev
          name: Install dependencies
      - run:
          command: pipenv run pytest --cov 
          name: Test
      - run:
          command: pipenv run pylint ./workoutshare
          name: Lint
workflows:
  main:
    jobs:
      - build
