# Generated by Django 4.1.6 on 2023-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
