# Generated by Django 4.1.6 on 2023-02-15 15:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_exercice_cool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='cool',
            field=models.DurationField(default=180, validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=599))]),
        ),
    ]
