# Generated by Django 4.1.6 on 2023-02-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_exercice_cool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='load',
        ),
        migrations.AlterField(
            model_name='exercice',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
