# Generated by Django 4.1.6 on 2023-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_exercice_load_alter_exercice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
