# Generated by Django 4.1.6 on 2023-03-17 10:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_exercice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='cool',
            field=models.DurationField(default='3:00', validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=599)), django.core.validators.MinValueValidator(datetime.timedelta(0))]),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='reps',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='sets',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
