# Generated by Django 4.1.6 on 2023-03-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='program_id',
            new_name='try_program',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='try_user',
        ),
    ]
