# Generated by Django 4.1.6 on 2023-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_following_author_remove_following_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.EmailField(max_length=25, unique=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
